/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      animation: {
        "blurred-fade-in": "blurred-fade-in 0.9s ease-in-out both",
        "fade-in": "fade-in 0.6s ease-in both",
        "fade-out": "fade-out 0.6s ease-out both",
        "slide-in-top": "slide-in-top 0.6s ease-out both",
        "slide-zoom-in-top": "slide-zoom-in-top 0.6s ease-out both",
        "slide-zoom-out-top": "slide-zoom-out-top 0.6s ease-out both",
        "slide-in-bottom": "slide-in-bottom 0.6s ease-out both",
        "slide-out-top": "slide-out-top 0.6s ease-out both",
        "slide-out-bottom": "slide-out-bottom 0.6s ease-out both",
        "zoom-in": "zoom-in 0.6s ease-out both",
        "zoom-out": "zoom-out 0.6s ease-out both",
        "slide-in-left": "slide-in-left 0.6s ease-out both",
        "slide-in-right": "slide-in-right 0.6s ease-out both",
        "slide-out-left": "slide-out-left 0.6s ease-out both",
        "slide-out-right": "slide-out-right 0.6s ease-out both",
        "fade-in-up": "fade-in-up 0.6s ease-in-out both",
        "fade-in-down": "fade-in-down 0.6s ease-in-out both",
        "fade-in-left": "fade-in-left 0.6s ease-in-out both",
        "fade-in-right": "fade-in-right 0.6s ease-in-out both",
        "fade-out-up": "fade-out-up 0.6s ease-out both",
        "fade-out-down": "fade-out-down 0.6s ease-out both",
        "fade-out-left": "fade-out-left 0.6s ease-out both",
        "fade-out-right": "fade-out-right 0.6s ease-out both",
      },
      keyframes: {
        "slide-zoom-in-top": {
          "0%": { transform: "scale(0.90) translateY(-50px)" },
          "100%": { transform: "scale(1) translateY(0)" },
        },
        "slide-zoom-out-top": {
          "0%": { transform: "scale(1) translateY(0)" },
          "100%": { transform: "scale(0.90) translateY(-50px)" },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "fade-out": {
          "0%": { opacity: "1" },
          "100%": { opacity: "0" },
        },
        "slide-in-top": {
          "0%": { transform: "translateY(-20px)" },
          "100%": { transform: "translateY(0)" },
        },
        "slide-in-bottom": {
          "0%": { transform: "translateY(20px)" },
          "100%": { transform: "translateY(0)" },
        },
        "slide-out-top": {
          "0%": { transform: "translateY(0)" },
          "100%": { transform: "translateY(-20px)" },
        },
        "slide-out-bottom": {
          "0%": { transform: "translateY(0)" },
          "100%": { transform: "translateY(20px)" },
        },
        "zoom-in": {
          "0%": { opacity: "0", transform: "scale(.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        "zoom-out": {
          "0%": { opacity: "1", transform: "scale(1)" },
          "100%": { opacity: "0", transform: "scale(.95)" },
        },

        "slide-in-left": {
          "0%": { transform: "translateX(-50px)" },
          "100%": { transform: "translateX(0)" },
        },
        "slide-in-right": {
          "0%": { transform: "translateX(50px)" },
          "100%": { transform: "translateX(0)" },
        },
        "slide-out-left": {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50px)" },
        },
        "slide-out-right": {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(50px)" },
        },

        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(50px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in-down": {
          "0%": { opacity: "0", transform: "translateY(-50px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in-left": {
          "0%": { opacity: "0", transform: "translateX(50px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        "fade-in-right": {
          "0%": { opacity: "0", transform: "translateX(-50px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        "fade-out-up": {
          "0%": { opacity: "1", transform: "translateY(0)" },
          "100%": { opacity: "0", transform: "translateY(-50px)" },
        },
        "fade-out-down": {
          "0%": { opacity: "1", transform: "translateY(0)" },
          "100%": { opacity: "0", transform: "translateY(50px)" },
        },
        "fade-out-left": {
          "0%": { opacity: "1", transform: "translateX(0)" },
          "100%": { opacity: "0", transform: "translateX(-50px)" },
        },
        "fade-out-right": {
          "0%": { opacity: "1", transform: "translateX(0)" },
          "100%": { opacity: "0", transform: "translateX(50px)" },
        },
      },
      animationDelay: {
        none: "0ms",
        0: "0ms",
        100: "100ms",
        150: "150ms",
        200: "200ms",
        250: "250ms",
        300: "300ms",
        400: "400ms",
        500: "500ms",
        700: "700ms",
        800: "800ms",
        900: "900ms",
        1000: "1000ms",
      },
      animationDuration: {
        none: "0ms",
        slower: "500ms",
        slow: "400ms",
        normal: "300ms",
        fast: "200ms",
        faster: "100ms",
        0: "0ms",
        100: "100ms",
        150: "150ms",
        200: "200ms",
        250: "250ms",
        300: "300ms",
        400: "400ms",
        500: "500ms",
        700: "700ms",
        800: "800ms",
        900: "900ms",
        1000: "1000ms",
      },
      animationSteps: {
        none: "0",
        retro: "8",
        normal: "16",
        modern: "24",
      },
      animationIterationCount: {
        none: "0",
        once: "1",
        twice: "2",
        thrice: "3",
        infinite: "infinite",
      },
      animationFillMode: {
        none: "none",
        forwards: "forwards",
        backwards: "backwards",
        both: "both",
      },
      animationCubicBezier: {
        "sine-in": "cubic-bezier(0.12,0,0.39,0)",
        "sine-out": "cubic-bezier(0.39,0.575,0.565,1)",
        "sine-in-out": "cubic-bezier(0.445,0.05,0.55,0.95)",
        "quad-in": "cubic-bezier(0.55,0.085,0.68,0.53)",
        "quad-out": "cubic-bezier(0.25,0.46,0.45,0.94)",
        "quad-in-out": "cubic-bezier(0.455,0.03,0.515,0.955)",
        "cubic-in": "cubic-bezier(0.55,0.055,0.675,0.19)",
        "cubic-out": "cubic-bezier(0.215,0.61,0.355,1)",
        "cubic-in-out": "cubic-bezier(0.645,0.045,0.355,1)",
        "quart-in": "cubic-bezier(0.895,0.03,0.685,0.22)",
        "quart-out": "cubic-bezier(0.165,0.84,0.44,1)",
        "quart-in-out": "cubic-bezier(0.77,0,0.175,1)",
        "quint-in": "cubic-bezier(0.755,0.05,0.855,0.06)",
        "quint-out": "cubic-bezier(0.23,1,0.32,1)",
        "quint-in-out": "cubic-bezier(0.86,0,0.07,1)",
        "expo-in": "cubic-bezier(0.95,0.05,0.795,0.035)",
        "expo-out": "cubic-bezier(0.19,1,0.22,1)",
        "expo-in-out": "cubic-bezier(1,0,0,1)",
        "circ-in": "cubic-bezier(0.6,0.04,0.98,0.335)",
        "circ-out": "cubic-bezier(0.075,0.82,0.165,1)",
        "circ-in-out": "cubic-bezier(0.785,0.135,0.15,0.86)",
        "back-in": "cubic-bezier(0.6,-0.28,0.735,0.045)",
        "back-out": "cubic-bezier(0.175,0.885,0.32,1.275)",
        "back-in-out": "cubic-bezier(0.68,-0.55,0.265,1.55)",
      },
    },
  },
  plugins: [],
};
